### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by scento** [egils/Cache#2]
There are different thinks I noticed while working with this project:
1. Nearly all code in this project uses the short array syntax `[]` to create new arrays. This syntax was introduced in PHP 5.4 - since many projects, which might depend on this project, support at least PHP 5.3, it might be useful to refactor the project regarding the full syntax.
2. `use`-clauses are always relative paths. This can lead to problems, when PHP is searching e.g. `DateTime` in `\Egils\Component\Cache\Adapter` and not in `\`.

**Comment by egils** [comment]
Regarding your questions:
1. That is a valid point and I though about it from the beginning. I was not sure if anyone else apart me actually need this lib. Once there is I do not mind refactoring it on master. However, I would like to keep minimum PHP version 5.4 (or even upgrade up to 5.5.9) on a separate branch and release both branches simultaneously for personal preference. 
2. This is not relevant since PHP 5.3.6 [bug](https://bugs.php.net/bug.php?id=50731) was resolved and `use`-statements accept only fully qualified classnames. So it is not possible right now that `DateTime` class imported with `use DateTime` would be searched within current namespace. Below is a quote from PHP [manual](http://php.net/manual/en/language.namespaces.importing.php) regarding this case:

> Note that for namespaced names (fully qualified namespace names containing namespace separator, such as Foo\Bar as opposed to global names that do not, such as FooBar), the leading backslash is unnecessary and not recommended, as import names must be fully qualified, and are not processed relative to the current namespace.

Thank you for your comments. Much appreciated! :star:

**Comment by mathroc** [comment]
Hi @egils 

I would recommend you _not_ to support php 5.3 as it has reached it's now [EOL](http://php.net/eol.php) 

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

**Comment by egils** [comment]
@mathroc I tend to agree with you. 
I have no knowledge about any PHP 5.3 dependant project that would want to use this lib. If there will be on I'll be more than happy to collaborate and help finding a solution. But for now I am closing this issue.

P.S. very nice read. Thank you!

**Comment by scento** [comment]
Okay, I just wanted to highlight, that we don't need to break backwards-compatibility.
